// apps/micro-frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { ExternalComponent } from './external/external.component';
import { EventService } from '@parvathyg/services';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'test-repo';

  constructor(private eventService: EventService) { }

  public navTools: any;

  ngOnInit(): void {
    this.navTools = [{ "name": "App1", "component": ExternalComponent, icon: "notifications.svg" }, { "name": "App2", "component": ExternalComponent, icon: "help.svg" }];
    this.eventService.on('show_notification', (data => this.filterNotification(data)));
    this.eventService.on('nav_action', (data => this.externalAction(data)));
  }

  public onNavAction(action) {
    console.log("Received event from nav-component - " + action);
    if (action === 'home') {
      window.open(`${environment.hostUrl}/acp-live`, "_self");
    }
  }

  filterNotification(data) {
    console.log('filter notifications for : ' + data.name);
  }

  externalAction(data) {
    console.log('event from external component : ' + data);
    // window.open(`${environment.hostUrl}/acp-live`, '_self');
  }
}

<div class="Wrapper">
  <div class="Container">
    <lib-navigation class="Navigation" (onNavAction)="onNavAction($event) "[externalComponents]="navTools"></lib-navigation>
    <div class="Content">
      <h1>Test Project!</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
        iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?</p>
    </div>
  </div>
</div>

// apps/react-acp-app/src/App.js
import React from 'react';
import './App.css';

import AcpSidenav from '@sidv93/react-acp-sidenav';

function App() {
  const homeUrl = window["homeUrl"];
  return (
    <div className="Wrapper">
      <div className="Container">
        <AcpSidenav className="Navigation" unreadCount={6} homeUrl={homeUrl} />
        <div className="Content">
          <h1>Test Project with React</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime aperiam sit officia consequuntur rem sapiente
            iure dolorum dolor dolores ullam, perspiciatis enim esse soluta, et ipsam molestias quisquam. Fugiat, aut?
          </p>
        </div>
      </div>
    </div>
  );
}

export default App;
